num1=34
num2=2.565
myname="mrs.sheila"
mybool1=True
mybool2=False
mybool3="emobilis"
mynum4=2+5j
mylist=[2,"python",7.96]
mylist2=[5,4,5,7,2,8,9,4]
mytuple=("sheila",3,"emobilis")
mylist[0]="esther"
print(type(myname))
print(type(mynum4))
print(type(mylist))
print(type(mybool3))
print(mylist[1])
print(mylist2[5])
print(sorted(mylist2))
print(mytuple[2]+ " is my school")
